networks:
  lmt-dev:
    driver: bridge
  traefik-proxy-blumilk-local:
    external: true

services:
  app:
    build:
      context: ./environment/dev/app
      dockerfile: Dockerfile
      args:
        - USER_ID=${DOCKER_HOST_USER_ID:-1000}
    labels:
      - "traefik.enable=true"
      - "traefik.blumilk.environment=true"
      # HTTP
      - "traefik.http.routers.lmt-http-router.rule=Host(`lmt.blumilk.localhost`)"
      - "traefik.http.routers.lmt-http-router.entrypoints=web"
      # HTTP to HTTPS redirect
      #      - "traefik.http.routers.lmt-http-router.middlewares=https-redirect@file"
      # HTTPS
      - "traefik.http.routers.lmt-https-router.rule=Host(`lmt.blumilk.localhost`)"
      - "traefik.http.routers.lmt-https-router.entrypoints=websecure"
      - "traefik.http.routers.lmt-https-router.tls=true"
    container_name: lmt-dev-app-container
    working_dir: /application
    volumes:
      - ./environment/dev/app/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./environment/dev/app/php.ini:/usr/local/etc/php/conf.d/zzz-overrides.ini:ro
      - ./environment/dev/app/php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-overrides.conf:ro
      - ./environment/dev/app/supervisord.conf:/etc/supervisor/custom-supervisord.conf:ro
      - .:/application
    ports:
      - ${DOCKER_APP_HOST_PORT:-8051}:80
    networks:
      - lmt-dev
      - traefik-proxy-blumilk-local
    restart: unless-stopped

  mailpit:
    image: axllent/mailpit:v1.20.3@sha256:762dd66a062738309e43ad8efce733e8db4a73bf6a38e369aeb547aecb897d27
    container_name: lmt-dev-mailpit-container
    ports:
      - ${EXTERNAL_MAILPIT_DASHBOARD_PORT:-8052}:8025
      - ${EXTERNAL_MAILPIT_SMTP_PORT:-8053}:1025
    networks:
      - lmt-dev
      - traefik-proxy-blumilk-local
    labels:
      - "traefik.enable=true"
      - "traefik.blumilk.environment=true"
      # HTTP
      - "traefik.http.routers.lmt-mailpit-http-router.rule=Host(`lmt-mailpit.blumilk.localhost`)"
      - "traefik.http.routers.lmt-mailpit-http-router.entrypoints=web"
      # HTTP to HTTPS redirect
      #      - "traefik.http.routers.lmt-mailpit-http-router.middlewares=https-redirect@file"
      # HTTPS
      - "traefik.http.routers.lmt-mailpit-https-router.rule=Host(`lmt-mailpit.blumilk.localhost`)"
      - "traefik.http.routers.lmt-mailpit-https-router.entrypoints=websecure"
      - "traefik.http.routers.lmt-mailpit-https-router.tls=true"
      # LOADBALANCER MAILHOG PORT
      - "traefik.http.services.lmt-mailpit.loadbalancer.server.port=8025"
    restart: unless-stopped
