version: '3.8'
networks:
  traefik-proxy-blumilk-local:
    external: true
  lmt-dev:
    driver: bridge

services:
  web:
    image: nginx:1.25-alpine
    container_name: lmt-dev-web
    volumes:
      - ./environment/dev/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/application
    ports:
      - ${EXTERNAL_WEBSERVER_PORT:-8051}:80
    networks:
      - lmt-dev
      - traefik-proxy-blumilk-local
    links:
      - php
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.blumilk.environment=true"
      - "traefik.http.routers.lmt-http-router.rule=Host(`lmt.blumilk.localhost`)"
      - "traefik.http.routers.lmt-http-router.entrypoints=web"
      - "traefik.http.routers.lmt-https-router.rule=Host(`lmt.blumilk.localhost`)"
      - "traefik.http.routers.lmt-https-router.entrypoints=websecure"
      - "traefik.http.routers.lmt-https-router.tls=true"

  php:
    image: ghcr.io/blumilksoftware/php:8.3
    container_name: lmt-dev-php
    working_dir: /application
    user: ${CURRENT_UID:-1000}
    volumes:
      - .:/application
    ports:
      - ${EXTERNAL_PHP_PORT:-8048}:9000
    networks:
      - lmt-dev
      - traefik-proxy-blumilk-local
    labels:
      - "traefik.enable=true"
      - "traefik.blumilk.environment=true"
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: lmt-dev-mailhog
    ports:
      - ${EXTERNAL_MAILHOG_PORT:-8050}:1025
      - ${EXTERNAL_MAILHOG_DASHBOARD_PORT:-8049}:8025
    networks:
      - lmt-dev
      - traefik-proxy-blumilk-local
    labels:
      - "traefik.enable=true"
      - "traefik.blumilk.environment=true"
      # HTTP
      - "traefik.http.routers.lmt-mailhog-http-router.rule=Host(`lmt-mailhog.blumilk.localhost`)"
      - "traefik.http.routers.lmt-mailhog-http-router.entrypoints=web"
      # HTTP to HTTPS redirect
      #      - "traefik.http.routers.lmt-mailhog-http-router.middlewares=https-redirect@file"
      # HTTPS
      - "traefik.http.routers.lmt-mailhog-https-router.rule=Host(`lmt-mailhog.blumilk.localhost`)"
      - "traefik.http.routers.lmt-mailhog-https-router.entrypoints=websecure"
      - "traefik.http.routers.lmt-mailhog-https-router.tls=true"
      # LOADBALANCER MAILHOG PORT
      - "traefik.http.services.lmt-mailhog.loadbalancer.server.port=8025"
    restart: unless-stopped
