networks:
  lmt-local:
    driver: bridge
  traefik-proxy-blumilk-local-environment:
    external: true

volumes:
  lmt-postgres-data:
    name: lmt-postgres-data

services:
  app:
    container_name: lmt-app-local
    build:
      context: .
      dockerfile: environment/.docker/app/Dockerfile
      target: local
      args:
        - INSTALL_XDEBUG=${DOCKER_INSTALL_XDEBUG:-false}
        - USER_ID=${DOCKER_HOST_USER_ID:-1000}
    labels:
      - "traefik.enable=true"
      - "traefik.blumilk.local.environment=true"
      # HTTP
      - "traefik.http.routers.lmt-http-router.rule=Host(`${APP_DOCKER_HOST_NAME}`)"
      - "traefik.http.routers.lmt-http-router.entrypoints=web"
      - "traefik.http.routers.lmt-http-router.service=lmt-app"
      # HTTPS
      - "traefik.http.routers.lmt-https-router.rule=Host(`${APP_DOCKER_HOST_NAME}`)"
      - "traefik.http.routers.lmt-https-router.entrypoints=websecure"
      - "traefik.http.routers.lmt-https-router.tls=true"
      - "traefik.http.routers.lmt-https-router.service=lmt-app"
      # APP LOADBALANCER
      - "traefik.http.services.lmt-app.loadbalancer.server.port=80"
      # VITE DEV SERVER
      - "traefik.http.routers.lmt-vite-dev-server-https-router.rule=Host(`${VITE_DEV_SERVER_DOCKER_HOST_NAME}`)"
      - "traefik.http.routers.lmt-vite-dev-server-https-router.entrypoints=websecure"
      - "traefik.http.routers.lmt-vite-dev-server-https-router.tls=true"
      - "traefik.http.routers.lmt-vite-dev-server-https-router.service=lmt-vite-dev-server"
      - "traefik.http.services.lmt-vite-dev-server.loadbalancer.server.port=5173"
    working_dir: /application
    volumes:
      - ./environment/local/app/php.ini:/usr/local/etc/php/conf.d/zzz-overrides.ini:ro
      - ./environment/local/app/php-fpm.conf:/usr/local/etc/php-fpm.d/zzz-overrides.conf:ro
      - ./environment/local/app/supervisord.conf:/etc/supervisor/custom-supervisord.conf:ro
      - .:/application
    ports:
      - ${DOCKER_APP_HOST_PORT:-8051}:80
    networks:
      - lmt-local
      - traefik-proxy-blumilk-local-environment
    restart: unless-stopped

  database:
    build:
      context: .
      dockerfile: environment/.docker/postgres/Dockerfile
    container_name: lmt-db-local
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - PGDATA=/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --dbname ${DB_DATABASE} --username ${DB_USERNAME}" ]
      interval: 3s
      timeout: 3s
      retries: 5
    ports:
      - ${DOCKER_DATABASE_HOST_PORT:-5432}:5432
    volumes:
      - lmt-postgres-data:/var/lib/postgresql/data
    networks:
      - lmt-local
    restart: unless-stopped

  mailpit:
    image: axllent/mailpit:v1.27.1@sha256:986b14ff7b253e62883ea19fd3112806f116e5e2f221e03f12fb81c7312ff532
    container_name: lmt-mailpit-local
    ports:
      - ${EXTERNAL_MAILPIT_DASHBOARD_PORT:-8052}:8025
      - ${EXTERNAL_MAILPIT_SMTP_PORT:-8053}:1025
    networks:
      - lmt-local
      - traefik-proxy-blumilk-local-environment
    labels:
      - "traefik.enable=true"
      - "traefik.blumilk.local.environment=true"
      # HTTP
      - "traefik.http.routers.lmt-mailpit-http-router.rule=Host(`${MAILPIT_DOCKER_HOST_NAME}`)"
      - "traefik.http.routers.lmt-mailpit-http-router.entrypoints=web"
      # HTTPS
      - "traefik.http.routers.lmt-mailpit-https-router.rule=Host(`${MAILPIT_DOCKER_HOST_NAME}`)"
      - "traefik.http.routers.lmt-mailpit-https-router.entrypoints=websecure"
      - "traefik.http.routers.lmt-mailpit-https-router.tls=true"
      # LOADBALANCER MAILPIT PORT
      - "traefik.http.services.lmt-mailpit.loadbalancer.server.port=8025"
    restart: unless-stopped
