# https://taskfile.dev
version: "3.42.1"

silent: true

tasks:
  deploy:
    deps: [create-deployment-file, decrypt-secrets, decrypt-json-files]
    vars:
      DOCKER_COMPOSE_FILE: docker-compose.dev.yml
      DOCKER_COMPOSE_APP_SERVICE: lmt-dev-app
      POST_DEPLOY_SCRIPT_FILE: post-deploy-actions.sh
    cmds:
      - cmd: docker compose --file {{ .DOCKER_COMPOSE_FILE }} pull
      - cmd: docker compose --file {{ .DOCKER_COMPOSE_FILE }} up --detach
      - cmd: sleep 5
      - cmd: echo "Run app post deploy actions"
      - cmd: docker compose --file {{ .DOCKER_COMPOSE_FILE }} exec --user www-data --workdir /application/environment/.deployment/scripts {{ .DOCKER_COMPOSE_APP_SERVICE }} bash {{ .POST_DEPLOY_SCRIPT_FILE }}

  decrypt-secrets:
    requires:
      vars: [SOPS_AGE_KEY]
    vars:
      DOTENV_FILE: .env.dev
      SECRETS_FILE: .env.dev.secrets
    cmds:
      - cmd: echo "Moving {{ .DOTENV_FILE }} to .env"
      - cmd: mv {{ .DOTENV_FILE }} .env
      - cmd: echo "Decrypting secrets from {{ .SECRETS_FILE }}"
      - cmd: sops --decrypt --input-type=dotenv --output-type=dotenv {{ .SECRETS_FILE }} >> .env
      - cmd: echo "Done"

  decrypt-json-files:
    requires:
      vars: [SOPS_AGE_KEY]
    vars:
      FILES: [firebase-credentials-customer.json, firebase-credentials-partner.json]
    cmds:
      - cmd: echo "Decrypting json files"
      - for: { var: FILES, as: FILE }
        cmd: |
          echo "Decrypting {{ .FILE }}.encrypted file"
          sops --decrypt --input-type=json --output-type=json --output={{ .FILE }} {{ .FILE }}.encrypted
      - cmd: echo "Done"

  create-deployment-file:
    vars:
      DATETIME:
        sh: TZ=Europe/Warsaw date --rfc-3339=seconds
    cmds:
      - cmd: echo "DEPLOY_DATE='{{ .DATETIME }}'" >> .deployment
