networks:
  traefik-proxy:
    external: true
  lmt-prod-app:
    driver: bridge

services:
  lmt-prod-app:
    image: ghcr.io/blumilksoftware/lmt:prod
    container_name: lmt-prod-app-container
    pull_policy: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 1GB
    labels:
      - "io.portainer.accesscontrol.teams=LMT"
      - "traefik.enable=true"
      - "traefik.http.routers.lmt-prod-app.rule=Host(`${LMT_HOST_NAME}`)"
      - "traefik.http.routers.lmt-prod-app.entrypoints=websecure"
      - "traefik.http.routers.lmt-prod-app.tls=true"
      - "traefik.http.routers.lmt-prod-app.tls.certresolver=lets-encrypt-resolver"
      - "traefik.http.routers.lmt-prod-app.middlewares=response-gzip-compress@file"
    working_dir: /application
    volumes:
      - ./.env:/application/.env:ro
    networks:
      - lmt-prod
      - traefik-proxy
    restart: unless-stopped
    env_file:
      - .deployment